// src/ui/components/MapComponent.vue
<template>
  <div id="map" @click="onClick" @contextmenu.prevent.stop="onContextMenu">
    <div class="controls bottom-left column" @contextmenu.stop="">
      <div class="mapbox-wordmark">
        <a
          href="https://www.mapbox.com/about/maps/"
          title="Map tiles and styling provided by Mapbox"
        >
          <img :src="MAPBOX_WORDMARK_IMAGE_DATA" height="18" alt="Mapbox" />
        </a>
      </div>

      <div id="overview-map" title="Change base map" @click="nextBaseLayer()">
        <div class="label">{{ nextBaseLayerLabel }}</div>
      </div>
    </div>

    <div class="controls bottom-right column">
      <button
        type="button"
        title="Find my location"
        class="material-icons"
        @click="zoomToUserLocation()"
      >
        my_location
      </button>

      <button
        title="Zoom to full extent"
        class="material-icons hidden-xs"
        @click="map.setInitialCenterAndZoom()"
      >
        public
      </button>

      <button
        type="button"
        title="Zoom in"
        class="material-icons"
        @click="map.zoomIn()"
      >
        add
      </button>

      <button
        type="button"
        title="Zoom out"
        class="material-icons"
        @click="map.zoomOut()"
      >
        remove
      </button>

      <button
        type="button"
        title="Change base map"
        class="material-icons visible-sm"
        @click="nextBaseLayer()"
      >
        layers
      </button>
    </div>

    <div id="attributions" @contextmenu.stop="">
      <div class="mapbox-copyright">
        © <a href="https://www.mapbox.com/about/maps/">Mapbox</a>
      </div>

      <div class="osm-copyright">
        © <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>
      </div>

      <div class="mapbox-improve">
        <a href="https://www.mapbox.com/map-feedback/">Improve this map</a>
      </div>
    </div>

    <MapContextMenu />
    <StopInfo />
  </div>
</template>

<script setup lang="ts">
import { inject, onMounted, ref, watch } from "vue";

import VectorLayer from "ol/layer/Vector";
import VectorSource from "ol/source/Vector";

import { STREET_LEVEL_ZOOM, MAPBOX_WORDMARK_IMAGE_DATA } from "../const";
import { useStore } from "../store";

import MapService from "./MapService";
import { STOP_STYLE_SELECTED } from "./map-styles";
import MapContextMenu from "./MapContextMenu.vue";
import StopInfo from "./StopInfo.vue";

const store = useStore();
const map: MapService = inject("map") as MapService;
const numBaseLayers = map.getBaseLayers().length;
const nextBaseLayerLabel = ref(map.getNextBaseLayer().get("shortLabel"));
const stopsLayer = map.getLayer("Stops") as VectorLayer<VectorSource>;
const stopsSource = stopsLayer.getSource() as VectorSource;

watch(
  () => store.baseLayer,
  (newBaseLayer) => {
    map.setBaseLayer(newBaseLayer);
    nextBaseLayerLabel.value = map.getNextBaseLayer().get("shortLabel");
  }
);

watch(
  () => store.result,
  (newResult, oldResult) => {
    if (oldResult) {
      oldResult.stops.forEach((stop: any) => {
        const feature = stopsSource.getFeatureById(`stop.${stop.id}`);
        if (feature) {
          feature.setStyle(undefined);
        }
      });
    }

    if (newResult && newResult.stops.length) {
      const stops = newResult.stops;
      const newExtent = map.extentOf(stops, true);

      const setStyle = () => {
        stops.forEach((stop: any) => {
          const feature = stopsSource.getFeatureById(`stop.${stop.id}`);
          if (feature) {
            feature.setStyle(STOP_STYLE_SELECTED);
          }
        });
      };

      if (!map.containsExtent(newExtent) || map.getZoom() < STREET_LEVEL_ZOOM) {
        map.setExtent(newExtent, () => map.once("rendercomplete", setStyle));
      } else {
        setStyle();
      }
    }
  }
);

function nextBaseLayer() {
  store.nextBaseLayer({ numBaseLayers });
}

function zoomToUserLocation() {
  const userLocation = map.getUserLocation();
  if (userLocation.position) {
    map.showUserLocation(/*zoomTo*/ true);
  } else {
    store.setError({
      title: "Location Error",
      explanation: "Could not determine your location.",
      detail: "Check your browser location settings and try again.",
    });
  }
}

function onClick() {
  store.closeMapContextMenu();
}

function onContextMenu(event: any) {
  const x = event.pageX;
  const y = event.pageY;
  store.setMapContextMenuState({ open: true, x, y });
}

onMounted(() => {
  map.onFeature(
    "click",
    (map, feature) => {
      const stopID = feature.get("id");
      if (store.error) {
        store.resetSearchState();
      }
      store.toggleStopID({ stopID });
      store.search({ term: store.term });
    },
    () => {
      store.resetSearchState();
    },
    stopsLayer
  );

  // Initial zoom to user location
  map.addGeolocatorListener(
    "change",
    () => map.showUserLocation(/* zoomTo */ true),
    /* once */ true
  );

  map.addGeolocatorListener("change", () => map.showUserLocation());

  map.addGeolocatorListener(
    "error",
    (error) => {
      let explanation;
      let detail;

      switch (error.code) {
        case 1:
          explanation =
            "Access to location services have been disabled for this site.";
          detail = "Check your browser location settings and try again.";
          break;
        case 3:
          explanation = "Could not find your location after 30 seconds.";
          break;
        default:
          explanation = "Could not determine your location.";
      }

      store.setError({
        title: "Location Error",
        explanation,
        detail,
      });
    },
    /*once */ true
  );
});
</script>

<style scoped lang="scss">
@import "../assets/styles/mixins";
@import "../assets/styles/variables";

#map {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1;
  background-color: lighten(lightseagreen, 50%);
  user-select: none;
}

#map > .controls {
  position: absolute;
  z-index: 1;

  button {
    @include floating-element();
  }

  &.row {
    display: flex;
    flex-direction: row;
    margin: 0;
    > * {
      margin: 0;
      margin-left: $quarter-standard-spacing;
    }
  }

  &.column {
    display: flex;
    flex-direction: column;
    margin: 0;
    > * {
      margin: 0;
      margin-top: $quarter-standard-spacing;
    }
  }

  &.bottom-left {
    bottom: $standard-spacing;
    left: $standard-spacing;

    #overview-map {
      @include floating-element();
      @include hidden-sm();

      position: relative;

      width: 128px;
      height: 128px;

      background-color: white;
      border: 2px solid lightgray;
      border-radius: $border-radius;
      cursor: pointer;
      margin-bottom: $quarter-standard-spacing;

      .label {
        position: absolute;
        right: 0;
        bottom: 0;
        left: 0;
        margin: 0;
        padding: 2px;
        z-index: 10;
        color: black;
        background-color: rgba(255, 255, 255, 0.5);
        font-weight: bold;
        line-height: 1;
        text-align: center;
      }
    }
    @media (max-width: $sm-width - 1px) {
      bottom: $standard-spacing + 28px;
    }

    @media (max-width: $xs-width - 1px) {
      left: $quarter-standard-spacing;
      bottom: $half-standard-spacing + 20px;
    }
  }

  &.bottom-right {
    bottom: $standard-spacing;
    right: $standard-spacing;

    @media (max-width: $xs-width - 1px) {
      bottom: $quarter-standard-spacing;
      right: $quarter-standard-spacing;
    }
  }
}

#map > #attributions {
  @include floating-element();
  @include hidden-sm();

  position: absolute;
  bottom: $standard-spacing;
  right: $standard-spacing + $half-standard-spacing + 40px;
  z-index: 12;

  background-color: rgba(255, 255, 255, 0.75);

  font-size: 14px;
  line-height: 1;
  padding: 8px 4px;
  white-space: nowrap;

  .mapbox-improve a {
    font-weight: bold;
  }

  div {
    display: inline-block;
    margin-right: $quarter-standard-spacing;
    &:last-child {
      margin-right: 0;
    }
  }
}
</style>

// src/ui/map/Map.tsx
import "./Map.scss";
import * as React from "react";
import { renderToString } from "react-dom/server";

import { useAppDispatch, useAppSelector } from "../hooks";
import { closeMainMenu, setBottomSheetContent } from "../slice";
import { resetSearchState, search, selectSelectedStops, setError } from "../search/slice";

import { MAPBOX_WORDMARK_IMAGE_DATA } from "./const";

import {
  initialState,
  openContextMenu,
  selectCenter,
  selectZoom,
  selectBaseLayer,
  zoomIn,
  zoomOut,
  setBaseLayer,
  setCenter,
  setZoom,
  setExtent,
  setResolution,
  selectExtent,
  setSize,
  setUserLocation,
  selectUserLocation,
} from "./slice";

import Attributions from "./Attributions";
import ContextMenu from "./ContextMenu";
import StopInfo from "./StopInfo";
import OpenLayersMap from "./OpenLayersMap";

const Map = () => {
  const mapRef = React.useRef<OpenLayersMap | null>(null);
  const mapElRef = React.useRef(null);
  const overviewMapRef = React.useRef(null);

  const dispatch = useAppDispatch();

  const baseLayer = useAppSelector(selectBaseLayer);
  const center = useAppSelector(selectCenter);
  const zoom = useAppSelector(selectZoom);
  const extent = useAppSelector(selectExtent);
  const userLocation = useAppSelector(selectUserLocation);
  const selectedStops = useAppSelector(selectSelectedStops);

  const [stopFeature, setStopFeature] = React.useState<any>(null);

  // These send dispatched signals to the OL map
  React.useEffect((): any => mapRef.current?.setBaseLayer(baseLayer), [baseLayer]);
  React.useEffect((): any => mapRef.current?.setCenter(center, zoom), [center, zoom]);
  React.useEffect((): any => mapRef.current?.fitExtent(extent), [extent]);
  React.useEffect((): any => mapRef.current?.setSelectedStops(selectedStops), [selectedStops]);
  React.useEffect((): any => mapRef.current?.showUserLocation(userLocation), [userLocation]);

  React.useEffect(() => {
    if (mapRef.current) {
      return;
    }
    mapRef.current = new OpenLayersMap();
  }, [mapRef.current]);

  React.useEffect(() => {
    const map = mapRef.current;

    if (!map) {
      return;
    }

    const stopsLayer = map.getFeatureLayer("Stops");

    map.initialize(mapElRef.current, overviewMapRef.current);

    map.setCenter(center, zoom).then(() => {
      map.addListener("moveend", () => {
        dispatch(setCenter(map.getCenter()));
        dispatch(setZoom(map.getZoom()));
        dispatch(setExtent(map.getExtent()));
        dispatch(setResolution(map.getResolution()));
        dispatch(setSize(map.getSize()));
      });

      map.addFeatureListener(
        "singleclick",
        (feature) => dispatch(search(feature.get("id").toString(), true, true)),
        () => dispatch(resetSearchState()),
        stopsLayer
      );

      map.addListener("movestart", () => {
        if (stopFeature) {
          setStopFeature(null);
        }
      });

      map.addFeatureListener(
        "pointermove",
        (feature) => {
          if (feature !== stopFeature) {
            setStopFeature(feature);
          }
        },
        () => setStopFeature(null),
        stopsLayer,
        10
      );

      map.addGeolocatorListener("change", () => {
        const position = map.geolocator.getPosition();
        const accuracy = map.geolocator.getAccuracy();
        const accuracyCoords = map.geolocator.getAccuracyGeometry().getCoordinates();
        const heading = map.geolocator.getHeading() || 0;
        dispatch(setUserLocation({ position, accuracy, accuracyCoords, heading, error: null }));
      });

      map.addGeolocatorListener(
        "change",
        () => dispatch(setCenter({ center: map.geolocator.getPosition(), zoom: 18 })),
        true
      );

      map.addGeolocatorListener("error", (error) => {
        let errorMessage;

        switch (error.code) {
          case 1:
            errorMessage =
              "Access to location services have been disabled for this site. Check " +
              "your browser location settings and try again.";
            break;
          case 3:
            errorMessage = "Could not find location after 30 seconds.";
            break;
          default:
            errorMessage = "Could not determine location.";
        }

        dispatch(
          setError({
            title: "Could not access your location",
            message: errorMessage,
          })
        );

        dispatch(
          setUserLocation({
            position: null,
            accuracy: Infinity,
            accuracyCoords: null,
            heading: null,
            error: errorMessage,
          })
        );
      });
    });

    return () => map.dispose();
  }, [mapRef.current]);

  return (
    <div
      className="Map"
      ref={mapElRef}
      onContextMenu={(event) => {
        event.preventDefault();
        const top = event.pageY;
        const left = event.pageX;
        setStopFeature(null);
        dispatch(closeMainMenu());
        dispatch(openContextMenu([top, left]));
      }}
    >
      <div
        className="controls bottom-right column"
        onContextMenu={(event) => {
          event.preventDefault();
          event.stopPropagation();
        }}
      >
        <button
          type="button"
          title="Find my location"
          className="material-icons"
          onClick={() => {
            const center = userLocation.position;
            if (center) {
              dispatch(setCenter({ center }));
            }
          }}
        >
          my_location
        </button>

        <button
          title="Zoom to full extent"
          className="material-icons hidden-xs"
          onClick={() =>
            dispatch(setCenter({ center: initialState.center, zoom: initialState.zoom }))
          }
        >
          public
        </button>

        <button title="Zoom in" className="material-icons" onClick={() => dispatch(zoomIn())}>
          add
        </button>

        <button title="Zoom out" className="material-icons" onClick={() => dispatch(zoomOut())}>
          remove
        </button>

        <button
          title="Map info"
          className="material-icons visible-sm"
          onClick={() => {
            const attributions = renderToString(Attributions({ title: "Map data and tiles" }));
            dispatch(
              setBottomSheetContent(`
                  <div style={{ textAlign: "center" }}>
                    <div>${attributions}</div>
                    <div>Site © 2018 mystops.io</div>
                </div>
            `)
            );
          }}
        >
          info
        </button>
      </div>
      <div
        className="controls bottom-left column"
        onContextMenu={(event) => {
          event.preventDefault();
          event.stopPropagation();
        }}
      >
        <div className="mapbox-wordmark">
          <a
            href="https://www.mapbox.com/about/maps/"
            title="Map tiles and styling provided by Mapbox"
          >
            <img src={MAPBOX_WORDMARK_IMAGE_DATA} height="18" />
          </a>
        </div>

        <div
          ref={overviewMapRef}
          className="overview-map"
          onClick={() => {
            dispatch(setBaseLayer(mapRef.current?.nextBaseLayer));
          }}
        >
          <div className="label">Layer</div>
        </div>
      </div>

      <Attributions />

      {mapRef.current && <ContextMenu map={mapRef.current} />}
      {mapRef.current && stopFeature && <StopInfo map={mapRef.current} feature={stopFeature} />}
    </div>
  );
};

export default Map;
