// src/mystops/components/ErrorComponent.tsx
import styled from "styled-components";

import { useStateContext } from "../state";

const Container = styled.div`
  position: absolute;
  top: 0;
  left: 0;
  width: var(--panel-width);
  z-index: 20;

  animation: fade-in 0.75s;
  background-color: white;
  box-shadow: 1px 1px 2px;
  color: red;
  margin: 0;
  padding: var(--half-standard-spacing);
  padding-top: calc(40px + var(--standard-spacing));

  @media (min-width: 600px) {
    padding: var(--standard-spacing);
    padding-top: calc(40px + var(--twice-standard-spacing));
  }
`;

const Title = styled.div`
  font-size: 20px;
  margin-bottom: var(--standard-spacing);
`;

export default function ErrorComponent() {
  const { state } = useStateContext();
  const { error } = state;

  if (!error) {
    return null;
  }

  return (
    <Container id="error">
      <Title>{error.title}</Title>
      <div>
        <p>{error.explanation}</p>
        {error.detail ? <p>{error.detail}</p> : null}
      </div>
    </Container>
  );
}

// src/ui/components/Error.vue
<template>
  <div id="error" v-if="error">
    <div id="title">
      {{ error.title }}
    </div>
    <div id="message">
      <p id="explanation">
        {{ error.explanation }}
      </p>
      <p id="detail" v-if="error.detail">
        {{ error.detail }}
      </p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, computed } from "vue";
import { useStore } from "../store";

export default defineComponent({
  name: "Error",
  setup() {
    const store = useStore();
    const error = computed(() => store.state.error);
    return { error };
  },
});
</script>

<style scoped lang="scss">
@import "../assets/styles/animations";
@import "../assets/styles/mixins";
@import "../assets/styles/variables";

#error {
  position: absolute;
  width: $panel-width;
  z-index: 2;
  animation: fade-in 0.75s;

  @include floating-element();

  background-color: white;
  color: red;
  margin: 0;
  padding: $standard-spacing;
  padding-top: 40px + $twice-standard-spacing;

  #title {
    font-size: 20px;
    margin-bottom: $standard-spacing;
  }

  #message:last-child {
    margin-bottom: 0;
  }

  @media (max-width: $xs-width - 1px) {
    padding: $half-standard-spacing;
    padding-top: 40px + $standard-spacing;
  }
}
</style>
