// src/mystops/static/old_app/components/MapContextMenu.tsx
import { useContext, useEffect } from "react";
import styled from "styled-components";

import { STREET_LEVEL_ZOOM } from "../const";
import MapContext from "./MapContext";

interface State {
  x: number;
  y: number;
  open: boolean;
}

interface Props {
  state: State;
  setState: ({ x, y, open }: State) => void;
}

const MenuContainer = styled.ul`
  position: absolute;
  z-index: 13;

  margin: 0;
  padding: 0;

  animation: fade-in 0.5s;
  background-color: white;
  border-radius: 2px;
  box-shadow: 2px 2px 4px;
  list-style: none;
`;

const MenuItem = styled.li`
  padding: var(--half-standard-spacing);

  &:hover {
    background-color: #f8f8f8;
    color: var(--link-color-hover);
    cursor: pointer;
  }
`;

export default function MapContextMenu({ state: { x, y, open }, setState }: Props) {
  const map = useContext(MapContext);

  // This will cause the menu to be closed on *any* click.
  useEffect(() => {
    const listener = () => setState({ x: 0, y: 0, open: false });
    document.addEventListener("click", listener);
    document.addEventListener("contextmenu", listener);
    return () => {
      document.removeEventListener("click", listener);
      document.removeEventListener("contextmenu", listener);
    };
  });

  if (!(map && open)) {
    return null;
  }

  const coord = map?.getCoordinateFromPixel([x, y]);
  const style = getStyle(map, x, y);

  const setCenter = (event) => {
    event.preventDefault();
    map.setCenter(coord);
  };

  const setCenterAndZoom = (event) => {
    event.preventDefault();
    if (map.getZoom() > STREET_LEVEL_ZOOM) {
      map.setCenter(coord);
    } else {
      map.setCenterAndZoom(coord, STREET_LEVEL_ZOOM);
    }
  };

  return (
    <MenuContainer id="map-context-menu" style={{ ...style }}>
      <MenuItem onClick={setCenter}>Center map here</MenuItem>
      <MenuItem onClick={setCenterAndZoom}>Zoom in here</MenuItem>
    </MenuContainer>
  );
}

const getStyle = (map, x: number, y: number) => {
  if (!open) {
    return {
      display: "none",
      top: "auto",
      right: 0,
      bottom: 0,
      left: "auto",
    };
  }

  const [containerWidth, containerHeight] = map.getSize() || [0, 0];
  const threshold = 200;

  let top = `${y}px`;
  let right = "auto";
  let bottom = "auto";
  let left = `${x}px`;

  if (containerWidth - x < threshold) {
    left = "auto";
    right = `${containerWidth - x}px`;
  }

  if (containerHeight - y < threshold) {
    top = "auto";
    bottom = `${containerHeight - y}px`;
  }

  return { display: "block", top, right, bottom, left };
};

// src/ui/components/MapContextMenu.vue
<template>
  <ul id="map-context-menu" v-if="open" :style="{ ...style }">
    <li>
      <a href="" @click.prevent="setCenter">Center map here</a>
    </li>
    <li>
      <a href="" @click.prevent="setCenterAndZoom">Zoom in here</a>
    </li>
  </ul>
</template>

<script setup lang="ts">
import { computed, inject } from "vue";
import { STREET_LEVEL_ZOOM } from "../const";
import { useStore } from "../store";
import MapService from "./MapService";

const store = useStore();
const map: MapService = inject("map") as MapService;
const open = computed(() => store.state.mapContextMenu.open);
const style = computed(() => getStyle(map, store.state.mapContextMenu));

function getCoordinate() {
  const { x, y } = store.state.mapContextMenu;
  return map.getCoordinateFromPixel([x, y]);
}

function setCenter() {
  map.setCenter(getCoordinate());
}

function setCenterAndZoom() {
  const center = getCoordinate();
  if (map.getZoom() > STREET_LEVEL_ZOOM) {
    map.setCenter(center);
  } else {
    map.setCenterAndZoom(center, STREET_LEVEL_ZOOM);
  }
}

function getStyle(
  map: MapService,
  state: { open: boolean; x: number; y: number }
) {
  if (!state.open) {
    return {
      display: "none",
      top: "auto",
      right: 0,
      bottom: 0,
      left: "auto",
    };
  }

  const { x, y } = state;
  const [containerWidth, containerHeight] = map.getSize() || [0, 0];
  const threshold = 200;

  let top = `${y}px`;
  let right = "auto";
  let bottom = "auto";
  let left = `${x}px`;

  if (containerWidth - x < threshold) {
    left = "auto";
    right = `${containerWidth - x}px`;
  }

  if (containerHeight - y < threshold) {
    top = "auto";
    bottom = `${containerHeight - y}px`;
  }

  return { display: "block", top, right, bottom, left };
}
</script>

<style scoped lang="scss">
@import "../assets/styles/animations";
@import "../assets/styles/mixins";
@import "../assets/styles/variables";

#map-context-menu {
  @include menu(
    $item-border: none,
    $item-padding: (
      $quarter-standard-spacing $half-standard-spacing,
    ),
    $item-link-color: $text-color
  );

  > li:first-child {
    border-top: 1px solid $menu-item-border-color;
  }

  position: absolute;
  z-index: 13;

  animation: fade-in 0.5s;
}
</style>
