// src/Menu.tsx
import { autobind } from 'core-decorators';

import * as React from 'react';
import { connect } from 'react-redux';

import { setBaseLayer, setMapContextMenuState, setMenuState } from './store';

import { DISCLAIMER } from './const';

import './Menu.css';
import { BASE_LAYER_LABELS } from './map';

interface IProps {
  menuOpen?: boolean;
  baseLayer?: string;
}

interface IDispatchProps {
  setBaseLayer: (label: string) => void;
  setMenuState: (open?: boolean) => void;
}

class Menu extends React.Component<IProps & IDispatchProps> {
  menuRef: any = React.createRef();

  render() {
    const props = this.props;
    const { menuOpen } = props;

    return (
      <div className="Menu" style={{ right: menuOpen ? 0 : 'auto' }}>
        <button
          type="button"
          title={menuOpen ? 'Hide menu' : 'Show menu'}
          className="material-icons"
          onClick={this.toggleMenu}
        >
          {menuOpen ? 'close' : 'menu'}
        </button>

        <div
          className="menu-backdrop"
          onClick={this.closeMenu}
          style={{ display: menuOpen ? 'block' : 'none' }}
        />

        <ul
          className="menu"
          ref={this.menuRef}
          onClick={this.handleClick}
          style={{ display: menuOpen ? 'block' : 'none' }}
        >
          <li className="title">MyStops</li>

          <li>
            <a href="/" className="regular-link">
              <span className="material-icons">home</span>
              <span>Home</span>
            </a>
          </li>

          {BASE_LAYER_LABELS.map(label => {
            return (
              <li key={label}>
                {label === props.baseLayer ? (
                  <div>
                    <span className="material-icons">layers</span>
                    <span>{label}</span>
                  </div>
                ) : (
                  <a
                    href="#switch-base-layer"
                    onClick={this.setBaseLayer.bind(this, label)}
                  >
                    <span className="material-icons">layers</span>
                    <span>{label}</span>
                  </a>
                )}
              </li>
            );
          })}

          <li className="section-heading">
            <span>Links</span>
          </li>

          <li>
            <a href="https://trimet.org/" className="regular-link">
              <span className="material-icons">link</span>
              <span>TriMet</span>
            </a>
          </li>

          <li className="section-heading">
            <span>Info</span>
          </li>

          <li className="info">
            <div>
              <p dangerouslySetInnerHTML={{ __html: DISCLAIMER }} />
              <p>&copy; 2018 mystops.io</p>
            </div>
          </li>
        </ul>
      </div>
    );
  }

  @autobind
  closeMenu() {
    this.props.setMenuState(false);
  }

  @autobind
  toggleMenu() {
    this.props.setMenuState(!this.props.menuOpen);
  }

  @autobind
  handleClick(event) {
    let target = event.target;
    while (target.tagName !== 'A') {
      target = target.parentNode;
      if (target === null || target === this.menuRef.current) {
        return false;
      }
    }
    if (!target.classList.contains('regular-link')) {
      event.preventDefault();
    }
    this.props.setMenuState(false);
    return true;
  }

  @autobind
  setBaseLayer(label) {
    this.props.setBaseLayer(label);
  }
}

function mapStateToProps(state) {
  return {
    ...state.main,
    ...state.map,
  };
}

function mapDispatchToProps(dispatch): IDispatchProps {
  return {
    setBaseLayer: label => {
      dispatch(setBaseLayer(label));
    },
    setMenuState: open => {
      dispatch(setMenuState(open));
      dispatch(setMapContextMenuState(false));
    },
  };
}

export default connect(mapStateToProps, mapDispatchToProps)(Menu as any);

// src/ui/components/MenuComponent.vue
<template>
  <div id="menu" :style="{ right: menuOpen ? 0 : 'auto' }">
    <button
      type="button"
      :title="buttonTitle"
      class="material-icons"
      @click="toggleMenu()"
    >
      <template v-if="menuOpen">close</template>
      <template v-else>menu</template>
    </button>

    <div class="menu-backdrop" @click="closeMenu()" v-if="menuOpen" />

    <ul class="menu" v-if="menuOpen">
      <li class="title">MyStops</li>

      <li>
        <a href="/" class="regular-link">
          <span class="material-icons">home</span>
          <span>Home</span>
        </a>
      </li>

      <li v-for="(layer, i) in layers" :key="i">
        <div v-if="i === baseLayer">
          <span class="material-icons">layers</span>
          <span>{{ layer }}</span>
        </div>
        <a v-else href="" @click.prevent="setBaseLayer(i)">
          <span class="material-icons">layers</span>
          <span>{{ layer }}</span>
        </a>
      </li>

      <li class="section-heading">
        <span>Links</span>
      </li>

      <li>
        <a href="https://trimet.org/" class="regular-link">
          <span class="material-icons">link</span>
          <span>TriMet</span>
        </a>
      </li>

      <li class="section-heading">
        <span>Info</span>
      </li>

      <li class="info">
        <div>
          <p>
            Arrival data provided by
            <a href="https://developer.trimet.org/">TriMet</a>.
          </p>
        </div>
      </li>

      <li class="info">
        <div>
          <p>
            Map data &copy; <a href="https://mapbox.com/">Mapbox</a> &
            <a href="https://openstreetmap.org/">OpenStreetMap</a>
          </p>
        </div>
      </li>

      <li class="info">
        <div>
          <p>
            This application is currently in the initial stages of development
            and <i>should not</i> be considered a reliable source for TriMet
            arrival times or any other information. Arrival times and other
            information <i>should</i> be verified via
            <a href="https://trimet.org/">TriMet's official TransitTracker™</a>
            or by other means.
          </p>
          <p>
            Contact: <a href="mailto:contact@mystops.io">contact@mystops.io</a>
          </p>
          <p>&copy; 2018, 2021 mystops.io</p>
        </div>
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { BASE_LAYER_LABELS } from "../const";
import { useStore } from "../store";

const store = useStore();

const menuOpen = computed(() => store.state.menuOpen);
const buttonTitle = computed(() =>
  store.state.menuOpen ? "Close menu" : "Open menu"
);
const layers = BASE_LAYER_LABELS;
const baseLayer = computed(() => store.state.baseLayer);
const setBaseLayer = (baseLayer: number) => {
  store.commit("setBaseLayer", { baseLayer });
  store.commit("closeMenu");
};
const closeMenu = () => store.commit("closeMenu");
const toggleMenu = () => store.commit("toggleMenu");
</script>

<style scoped lang="scss">
@import "../assets/styles/animations";
@import "../assets/styles/mixins.scss";
@import "../assets/styles/variables.scss";

#menu {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  z-index: 40;

  > button {
    position: absolute;
    top: $standard-spacing;
    left: $standard-spacing;
    z-index: 3;

    @media (max-width: $xs-width - 1px) {
      top: $quarter-standard-spacing;
      left: $quarter-standard-spacing;
    }
  }

  > div.menu-backdrop,
  ul.menu {
    animation: fade-in 0.5s;
  }

  > div.menu-backdrop {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 1;
    background-color: rgba(0, 0, 0, 0.5);
  }

  > ul.menu {
    @include menu();

    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    overflow: auto;
    z-index: 2;
    width: $menu-width;

    > li.title {
      @include title();
      text-align: right;

      &:hover {
        background-color: white;
      }
    }

    @media (max-width: $xs-width - 1px) {
      right: 0;
      width: auto;
    }
  }
}
</style>
